# For Cascade.Rmd
setwd("Models/Cascade/")
results %>% 
  filter(alpha == 0) %>% 
  .[perturbations,] %>% 
  mutate(perturbed = map_chr(pars_perturbed,~paste0(names(.x), collapse = ","))) %>% 
  select(perturbed, r_0, r_optupstream) %>% 
  mutate(r_0 = map_chr(r_0,~invisible(paste0("\\begin{equation*}", xtable:::print.xtable(xtable(.x), 
                                                                                                tabular.environment="pmatrix",
                                                                                                include.colnames = F,
                                                                                                include.rownames = F,
                                                                                                floating = F,
                                                                                                hline.after = NULL),
                                              
                                              "\\end{equation*} \n\n\n"))),
         r_optupstream = map_chr(r_optupstream,~invisible(paste0("\\begin{equation*}",
                                                                  xtable:::print.xtable(xtable(.x),
                                                                                        tabular.environment="pmatrix",
                                                                                        include.colnames = F,
                                                                                        include.rownames = F,
                                                                                        floating = F,
                                                                                        hline.after = NULL),
                                                                  "\\end{equation*} \n\n\n")
         ))) %>% 
  as.data.frame() %>% 
  as.matrix() %>% 
  apply(1, paste0, collapse = "&") %>% 
  paste0(collapse = "\\\\ \n") %>%
  paste0("\\begin{tabular}{ccc}",
         "Perturbed parameters & $r(\\vec{a} = 0)$ & $r(\\vec{a} = a_{opt})$ \\\\",
         ., "\\end{tabular}") %>%
  writeLines("matrices_many_different_perturbations.tex")

system2("pandoc", c("-o matrices_many_different_perturbations.docx", "matrices_many_different_perturbations.tex"))
writeLines("matrices_many_different_perturbations was generated by Script S7 in the main folder", "matrices_many_different_perturbationsREADME.txt")
