try(library(xtable))
try(library(MRAr))
try(library(conveniencefunctions))
try(library(here))
try(library(forcats))
try(library(stringr))
try(library(dplyr))
try(library(purrr))
try(library(readr))
try(library(tidyr))
try(library(tibble))
try(library(ggplot2))
try(library(tidyverse))
try(library(dMod))
try(library(cOde))
try(library(parallel))
try(library(stats))
try(library(graphics))
try(library(grDevices))
try(library(utils))
try(library(datasets))
try(library(methods))
try(library(base))
setwd('~/cascade3rep_rechecked_1_folder')
rm(list = ls())

load('cascade3rep_rechecked.RData')
files <- list.files(pattern = '.so')
for (f in files) dyn.load(f)
.node <- 1
.runbgOutput <- try({
    cores <- detectFreeCores()
    results <- run_different_perturbations_noisy_with_replicates(dose_pars = dose_pars, pars0 = pars, alpha_pars = alpha_pars, alphas = alphas, perturbations = perturbations, xs = xs, p_log = p_log, p_pert = p_pert, g = g, cores = cores, alpha_par_settings = alpha_par_settings, errorpars = error_pars, N = N, nreplicates = nreplicates)
    results
})
save(.runbgOutput, file = 'cascade3rep_rechecked_1_result.RData')