try(library(xtable))
try(library(MRAr))
try(library(conveniencefunctions))
try(library(forcats))
try(library(stringr))
try(library(dplyr))
try(library(purrr))
try(library(readr))
try(library(tidyr))
try(library(tibble))
try(library(ggplot2))
try(library(tidyverse))
try(library(dMod))
try(library(cOde))
try(library(parallel))
try(library(stats))
try(library(graphics))
try(library(grDevices))
try(library(utils))
try(library(datasets))
try(library(methods))
try(library(base))
setwd('~/hub_1_folder')
rm(list = ls())

load('hub.RData')
files <- list.files(pattern = '.so')
for (f in files) dyn.load(f)
.node <- 1
.runbgOutput <- try({
    cores <- detectFreeCores()
    alphas <- seq(-3, 3, 0.5)
    dose_pars <- pars[1]
    alpha_par_settings <- list(upstream = c("a_tox_Cxy", "a_tox_Cxz"), both = c("a_Cxy", "a_Cxz"))
    results <- run_different_perturbations(dose_pars = dose_pars, pars0 = pars, alpha_pars = alpha_pars, alphas = alphas, perturbations = perturbations, xs = xs, p_log = p_log, p_pert = p_pert, g = g, cores = cores, alpha_par_settings = alpha_par_settings)
    results
})
save(.runbgOutput, file = 'hub_1_result.RData')